### ISSUE TITLE
Loading the URDF file

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/icub-forward-kinematics-inspection#3]
Better off making available the load of the file from the command line using the ResourceFinder context instead of the [hand-coded file](https://github.com/mfussi66/icub-forward-kinematics-inspection/blob/master/src/fkinModule.cpp#L94).

Also, the URDF file could be stored in the repo as well.

**Comment by mfussi66** [comment]
The most recent version in master now provides the feature :+1:
